### ISSUE TITLE
Retweets and Replies Using twarc as library

### ISSUE THREAD

**Issue by adil-gikian** [DocNow/twarc#206]
Hi,

Thanks for doing providing us with an awesome library. I am a newbie and trying to learn how to use this library to get replies/ retweets of tweets using it as a library.

I know this is not an issue but request for information but I had no other way.

I couldn't figure it out on own and no help was there in the documentation. Can you please provide an example for getting replies and retweets for a tweet using Twarc as library. 

I tried using the following script but to no avail for replies.

```
for tweet in t.retweets(959170108013862912):
    print(tweet)

```
it wouldn't give any error but doesn't return the retweets also. and the same was tried for Replies but it gave an error.

**Comment by edsu** [comment]
Your code is correct but the tweet identifier you are using is for a retweet (that has not been retweeted) and not the original tweet. The tweet id you are checking is for this:

    https://twitter.com/DriftikharPTI/status/959170108013862912

Which is a retweet of:

    https://twitter.com/PTIofficial/status/959158463912988673

So try to adjust your code to get the retweets of the original tweet:

```python
for tweet in t.retweets('959158463912988673'):
    print(tweet)
```

You are right, the documentation for using twarc as a library is a bit sparse. The replies method takes a tweet JSON object as input, since it needs to introspect on some things. Here's an example:

```
import twarc

t = twarc.Twarc()

tweet = t.tweet('962206774630629376')

for tweet in t.replies(tweet, recursive=True):
    print(tweet['id_str'])
```

Note I have used the ids as strings. Also note that the replies command uses the search API which only returns data for the last two weeks. So you won't be able to use twarc to get replies to a tweet that is older than two weeks.

I hope this helps. Please feel free to reopen if not.
