### ISSUE TITLE
A better authentication error message

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#227]
There should be a better error message when a set of keys don't work:

```
Traceback (most recent call last):
  File "/usr/local/bin/twarc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/twarc/command.py", line 231, in main
    for thing in things:
  File "/usr/local/lib/python3.6/site-packages/twarc/client.py", line 213, in follower_ids
    raise e
  File "/usr/local/lib/python3.6/site-packages/twarc/client.py", line 209, in follower_ids
    resp = self.get(url, params=params, allow_404=True)
  File "/usr/local/lib/python3.6/site-packages/twarc/decorators.py", line 36, in new_f
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Authorization Required for url: https://api.twitter.com/1.1/followers/ids.json?screen_name=anarchivist&cursor=-1&tweet_mode=extended
```

**Comment by SamHames** [comment]
I've run into this in a few places, mainly attempting to retrieve tweets for now protected accounts. 

Am I right in my thinking that the fix for this would be to catch and raise a more specific error in the `rate_limit` decorator on a 401 response? One tricky part might be that the 401 could be because the credentials are bad, or just don't have access to that specific user if they're protected.

**Comment by edsu** [comment]
Yes, I think the difference between these two types of errrors is important for the user: invalid credentials vs lack of permission. I think the text of error message itself could be used to determine which one happened?

**Comment by SamHames** [comment]
That's what I was hoping, I'll do some investigation and submit a PR sometime in the next couple of days.

Another option is to use the [`account/verify_credentials`](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials.html) endpoint and hook that into the `check_keys` method. That might be a more little complex, but it would catch the invalid credentials case earlier and allow raising a specific error to the user rather than trying to parse an error message to disambiguate.
