### ISSUE TITLE
need dog-simple text output to cli

### ISSUE THREAD

**Issue by fredzannarbor** [DocNow/twarc#243]
i.e. gets rid of utf-8 b' ....'

**Comment by igorbrigadir** [comment]
Closing some old issues: In CLI, it should already output utf8 text, so this may depend on what shell you're running twarc in.

On windows, this issue comes up when using `>` to output to a file. Instead, you should specify the output file without the `>`. https://github.com/DocNow/twarc/issues/297 

If this is still an issue - please reopen with more details: what commands are you running, and what environment twarc is running in.
