### ISSUE TITLE
Convert format once downloaded

### ISSUE THREAD

**Issue by aborruso** [DocNow/twarc#253]
Hi all,
first of all thank you, it's really a great tool!!

A question: after I have made a twarc twitter search, is there a native way (an option, an utility) to convert from JSON to CSV?

Thank you

**Comment by hugovk** [comment]
There's a utility script called `json2csv.py` in the `utils` directory:

https://github.com/DocNow/twarc/blob/master/utils/json2csv.py

And see https://github.com/pbinkley/twarc-report for more.

**Comment by aborruso** [comment]
thank you

**Comment by aborruso** [comment]
@edsu thank you

**Comment by jeffcsauer** [comment]
Don't mean to necro this post, but is there anything special that needs to be done to `json2csv.py` in order to convert a .jsonl that results from a `twarc search`? For example, I have a 17MB twarc search .jsonl that I'm trying to convert to .csv via the following:

```cmd

pyhon json2csv.py tweets.jsonl > test.csv

```

The `test.csv` ends up empty, and I'm not getting any error messages.
