### ISSUE TITLE
Limit on replies

### ISSUE THREAD

**Issue by Gautamshahi** [DocNow/twarc#321]
Hello, I am crawling the replies and replies, but it's limited to 100 only. Is there any way to remove the limit?

**Comment by edsu** [comment]
Twarc uses the Twitter API. Unfortunately, Twitter's API call for retweets limited to the last 100 retweets. You may want to look at [twint](https://github.com/twintproject/twint) which scrapes Twitter's web interface.

Twarc's replies function is limited by how many of the tweets were in the last seven days, since it uses Twitter's search API.
