### ISSUE TITLE
Retweets cut off even while using extended tweet mode

### ISSUE THREAD

**Issue by harshbhatt** [DocNow/twarc#329]
Mainly want to know if I'm doing something wrong if this is expected behavior. Any retweet appears to be cut off with `...` at the end. However, on the person's timeline the full (re)tweet appears. Is there any way to extract it?

I've attached a sample generated CSV file, and here is the command I used:
`twarc --app_auth --format csv --tweet_mode extended --output w01_2020-01-26_TEST.csv`

[w01_2020-01-26_TEST.csv.zip](https://github.com/DocNow/twarc/files/4654651/w01_2020-01-26_TEST.csv.zip)

**Comment by edsu** [comment]
@harshbhatt thanks for reporting this. Can you include the actual command you used, the on you supplied is not complete.

**Comment by edsu** [comment]
@harshbhatt thanks again for reporting this. After reviewing the Twitter documentation about [Extended Tweets](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/intro-to-tweet-json#extendedtweet) it appears our logic for extracting the text of the tweet was not correct because it wasn't getting the text from the enclosed tweet:

> Again, when parsing Retweets, it is key to parse the "retweeted_status" object for complete (original) Tweet message and entity metadata.

This has been updated in v1.8.4 which was just released. Could you upgrade and give it a try, and reopen this ticket if you continue to have questions?

    pip install --upgrade twarc

**Comment by edsu** [comment]
Exellent, thanks @harshbhatt!
