### ISSUE TITLE
Send params to functions, like include_entities to false?

### ISSUE THREAD

**Issue by mspanish** [DocNow/twarc#336]
My app downloads followers fo users, and some have over 100,000 followers. Twarc can get these followers faster than any other script I've seen - but for a person with 100,000 followers it ends up being over 300MB of data. It would be great to have the simple option to set the params like include_entities in https://api.twitter.com/1.1/users/lookup.json so I can limit the amount of JSON transferred.

I'm new to Python so not sure how I can install my own custom version of Twarc - I guess I'll google that as this parameter is important!

**Comment by edsu** [comment]
Are you concerned about the time it takes to get users with entities from the Twitter API as compared to getting them without? If that's the case I don't think you should be overly concerned because in the end the rate limiting that Twitter imposes on API use will be much more significant. Or are you concerned about the size of the data? You can always write a little program to read through the JSON data and extract the values of interest and then discard the original data if you no longer need it.

twarc is oriented around *archiving* Twitter data: it tries to get the fullest representation of the various entities (tweets, users, etc) as it can. If you want to get more fine grained in what data is collected from the Twitter API and how I recommend you take a look at a libraries like [python-twarc](https://github.com/bear/python-twitter) or [tweepy](http://www.tweepy.org/), which give you a lot more control over how things are requested.

I'm sorry if this sounds dismissive of your question, but as we've developed this tool it has been important for us to keep twarc focused on the particular use case of collecting as much data as possible.

**Comment by mspanish** [comment]
Ah sure I understand, and actually the amount of data saved by excluding entities isn't nearly as much as the amount saved by saving only certain fields, and to CSV. The 300MB is looking like it will be closer to about 30 with my revised fields!

Thanks again - you are right and this is not very important.

**Comment by edsu** [comment]
Thank you for understanding @mspanish! Please let us know of more questions & suggestions as you encounter them!
