### ISSUE TITLE
hydrate with lang

### ISSUE THREAD

**Issue by p-dre** [DocNow/twarc#347]
Is there a way to compine hydrate with lang. 

Like: twarc hydrate ids.txt lang en > tweets.jsonl

I have a large list of ids and filtering within the query would significantly reduce the time and storage space

**Comment by edsu** [comment]
Unfortunately there's no way to cut down on the need to hydrate, because you can't determine the language from the tweet id itself. But you can pipe the data through a filter that only selects a particular language and then write that to disk. It won't cut down on the time, but it will cut down on the storage space.

Here's an example of a filter written as a small Python program:

```python
import json
import fileinput

for line in fileinput.input():
    tweet = json.loads(line)
    if tweet['lang'] == 'es':
        print(line, end='')
```

If you name that file langfilter.py you could use like this:

    twarc hydrate ids.txt | python langfilter.py > tweets.jsonl

If you are concerned about space you can pipe through a compression utility like gzip:

    twarc hydrate ids.txt | python filter.py | gzip - > tweets.jsonl.gz

**Comment by p-dre** [comment]
Unfortunately as I had already suspected. But thanks you for the comment this is really helpful for me.

**Comment by edsu** [comment]
Sure, good luck! The only other avenue might be to contact the creator of the tweet id dataset to see if they would be willing to create different tweet id datasets by language. Since they presumably still have the original data they might be willing to do that -- especially if it's a large volume of tweets.
