### ISSUE TITLE
foaf.py

### ISSUE THREAD

**Issue by ameliameyer** [DocNow/twarc#392]
When using foaf.py, I use the following usage command: python utils/foaf.py 2267720350  where 2267720350 is a user id gathered using the tweet.py utility but there is not output. Am I missing something?

**Comment by edsu** [comment]
Thanks for noticing this @ameliameyer! For some reason the code to actually gather the network was commented out. Maybe I was debugging it at some point and accidentally committed that back. This was a good opportunity to add a better description of what this utility is actually doing. It creates a SQLite database (named with the user id) to gather the user id links. The database is useful to keep track of which user ids have already been fetched. Then once the full network has been collected it looks up user information for each user id and stores that in the db. And once that is done it writes both tables to CSV files named after the user id. 

This one can take a long time to run because if someone follows someone with a million users that can trigger a lot of lookups. I kind of wanted to add another command line option to provide a limit for those. Let me know if that's of interest.

I'll leave this issue open until you confirm that the updated foaf.py is working for you.

**Comment by igorbrigadir** [comment]
Let us know if it worked - i would also suggest giving https://github.com/DocNow/twarc-network a try, it doesn't write to sqlite but does work with the same kind of data.
