### ISSUE TITLE
Retweets

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#403]
I think it would be useful to have a command like this:

    twarc2 retweets {tweet-url}

Which would fetch the retweets by looking up the conversation-id and then issuing the appropriate search. An optional `--archive` parameter could indicate whether to use the Academic Search endpoint.

**Comment by edsu** [comment]
Oh, I think I misread [the v2 search docs](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query). It looks like there's a way to get retweets of a particular user, but not retweets of a particular tweet?

**Comment by igorbrigadir** [comment]
The workaround for quote tweets is to use `(url:123 is:quote)` with the tweet id, and for retweets, `("text of tweet") retweets_of:user` or just `retweets_of:user` So i think we can definitely make this work.

**Comment by igorbrigadir** [comment]
There is now a new endpointforthis: https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/get-tweets-id-retweeted_by no need for a workaround

**Comment by edsu** [comment]
weird! I wonder why they did that?

**Comment by mr-devs** [comment]
Commenting here because I'm curious how you end up doing this... 😄 

I'm working on a project right now where we are trying to reconstruct retweet cascades and - to get all retweets in a cascade between time _X_ and time _Y_ - we utilize the `retweets_of:{user_id}` search parameter (as @igorbrigadir suggested above) with start and end times being _X_ and _Y_. `user_id` represents the user originating the cascade.

This approach returns a lot of extra retweets and then, after all the retweets are downloaded, we match the returned retweets to the original tweet's id number by using the `referenced_tweets` tweet field.

All of the cascades we are interested in contain links so we also include `has:links` in the query and you can keep adding in these types of filters to reduce the number of extra tweets that are returned in the query. I was hesitant to include the actual tweet text (because it seems like there might be some potential for weird behavior depending on each tweet's text) but I suppose that should work too!

**Comment by tnusser** [comment]
> There is now a new endpoint for this: https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/get-tweets-id-retweeted_by no need for a workaround
> 
> The interesting thing is, it returns Users as opposed to tweets - so this could create some interesting challenges for some types of analysis - mainly - it's hard to put a timestamp on the retweet.

This workaround has a limit of the 100 most recent retweeting users (without any pagination token), which makes it unpractical for cases where you need all of the retweets. 

The solution using `("text of tweet") retweets_of:user` does work for "simple" tweets only using regular characters but as soon as e.g. links or other user mentions are involved it fails too often, due to irregular characters etc. as @mr-devs already suspected.

**Comment by igorbrigadir** [comment]
Waiting to hear back from twitter on this proposal: https://github.com/twitterdev/open-evolution/pull/4

**Comment by igorbrigadir** [comment]
That above proposal was accepted, so that means at some point the idea will be considered (not guaranteed to be implemented) 

But recently the 100 latest result limit was lifted for retweets too: https://twittercommunity.com/t/updates-to-retweets-lookup-and-likes-lookup-endpoints/165327?u=igorbrigadir
