### ISSUE TITLE
Extend twarc2 configure to allow entering a bearer_token

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#405]
Possibly with a fast path to just enter a bearer token and an option to go down the more extensive path later if need be?

**Comment by SamHames** [comment]
I'd actually add that I think this one would be good to fix up before the first release :)

**Comment by igorbrigadir** [comment]
I've been thinking of how to make this as user friendly as possible. When creating a new app on the twitter dashboard, it gives you the bearer token first - so maybe the ideal flow would be:

`twarc configure`

> Enter you Bearer Token, or leave blank to generate it from an API Key and Secret: 

If Bearer token was provided, Continue with (Optional) Appended to the message - otherwise ensure that API Key and Secret is entered.

> Enter API Key:

> Enter API Secret:

At this point the rest of the flow if fine as is .. "How would you like twarc to obtain your user keys?" etc.

**Comment by SamHames** [comment]
That workflow is now in the V2 branch: the default authentication is bearer_token, with the option to use or add the rest of the keys as normal. Could use someone else running through the configure process to make sure I didn't miss anything.
