### ISSUE TITLE
flatten and line oriented tweets

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#473]
The `twarc2 flatten` command will make any expansions/fields inline to a tweet and also make the output file line oriented json -- where each line is a tweet.

It would be useful for plugin development if `twarc.expansions` contained a function (e.g. `jsonl`) that returned a list where every element was a tweet dictionary whether or not the object it was passed had a `data` key that was a list or an object.

I find myself repeating the [same conditional logic](https://github.com/DocNow/twarc-csv/blob/main/twarc_csv.py#L218-L225) in places where I want to process a file of tweets.

Does that make sense? Or maybe `flatten()` should just do it?

**Comment by SamHames** [comment]
For the record this is why I'm not a fan of flattened data for storage (and especially not --flatten): we've made more work for everything that consumes data because we need to think about non-standardised formats other than the original Twitter format. 

Since we've already opened this box though, it might be useful to consider an ensure_flattened function, which takes a stream of pages or already flattened tweets and returns an iterator of single tweet objects. In other words:

- ensure_flattened(original_twitter_pages) --> iterator of tweets
- ensure_flattened(flattened_tweets) --> iterator of tweets

**Comment by edsu** [comment]
Yes @SamHames I think I'm finally coming around to your idea that twarc2 should *always* write whatever the API gives it. Maybe I needed the experience of using `--flatten` in the wild to recognize what you suspected early on. 

Part of the difficulty here are the semantics of *flattened*.  `twarc.expansions.flatten` moves the includes in a response inline to the objects that reference them. It does *not* ensure that `response['data']` is a list as the streaming API returns `response['data']` as an object. This inconsistency has been introduced by the Twitter API and not by us, and it means any code that processes the data will need to peek at the type of `response['data']` in order to know what to do.

But maybe we can still put the genie back in the bottle? I propose that we: 

1. remove `--flatten` from all twarc2 sub-commands, but still offer `twarc2 flatten`, mostly for pipeline use.
2. update `twarc.expansions.flatten` so that it *always* returns a list of dictionary objects where each object is a tweet `{"id": "12345", "text": "Just setting up my twttr", "author": {"username": "jack"  ... ` 
3. add `twarc.expansions.ensure_flatten` that checks if data is flattened, and flattens if needed.
4. Plugins and other code that want to process flattened data can use `twarc.expansions.ensure_flattened` directly. 

Please vote with your thumbs: :+1:  :-1: or leave comments to propose changes to this plan.

**Comment by edsu** [comment]
I will interpret no votes as "I don't care do whatever you want" :-)

**Comment by igorbrigadir** [comment]
Yes, i agree with removing `--flatten` in favor of having `twarc2 flatten` for pipes and `ensure_flattened` that returns a list of dicts.

**Comment by edsu** [comment]
I've got some code on the [no-flat](https://github.com/docnow/twarc/tree/no-flat) branch that addresses this. If you are interested take a look. I'm going to hold off on merging it until I've updated the plugins we have to use twarc.ensure_flattened.

**Comment by igorbrigadir** [comment]
I don't think we should get rid of these lines: 

https://github.com/DocNow/twarc/commit/8b5bff4b8ec8ecb949a688568b306eb9d0b3b2cd#diff-f24fe70898891e79139147038d4d9050516192a55d61a9c7ff8bbb6faa30c292L195-L196

These lines expand the tweets in `includes.tweets` - so that they also have all the mentions, places, polls, geo etc. If these lines are left out, then we'll be losing data for tweets that were in includes, that also had expansions, for example: If we have a retweet of a poll, this would be in data, the original retweeted tweet will be inside `includes.tweets`, without expansions, and without this, we will miss the poll object in the `referenced_tweet` in our retweet

**Comment by edsu** [comment]
Thanks for catching that BIG mistake @igorbrigadir ... I would have thought that the unit tests would have caught it but they were only making sure that the `id` for a referenced tweet was defined, instead of a tweet property that would have actually been added by flattening. Whoops.

I updated the test to test correctly for flattened referenced tweets to see if it failed (it did) and then I added back these lines and it passed.
