### ISSUE TITLE
Any rate and cap limit with Twarc based Hydrating tweets? 

### ISSUE THREAD

**Issue by debrajde1** [DocNow/twarc#483]
I have a Twitter personal developer account. So I was trying to use "Twarc" tool to "hydrate" tweets (tweet IDs) for my personal (non-commercial and hobby) research project. I somehow was able to hydrate more than a million tweets without being given any warning on per month cap or rate limits. 

- Can you please let me know what is the limit for hydrating tweets for FREE account usage? I don't want to be billed anything and want to remain under free account limit. 

- In my "MONTHLY TWEET CAP USAGE", it says "0 Tweets pulled of 500,000". I am confused, does hydrating tweet count towards the 500,000?

**Comment by edsu** [comment]
It sounds like you are confusing the v1 and v2 APIs. This is easy to do since Twitter has made it confusing. The 500k limit is the cap for the Twitter v2 API. With the standard access to the v2 API you can't retrieve more then 500k tweets per month. If you exceed that amount of requests with the v2 API then you will get access denied over quota errors.

The v1 Twitter API has rate limits (but no monthly cap). You can do 900 requests per 15 minute window, each of which can fetch 100 tweets.  This means you can can request millions of tweets pretty easily. 

When you run `twarc` you are using the v1 API, so for example:

    twarc search politics > tweets.jsonl

And if you use `twarc2` you are using the v2 API:

    twarc2 search politics > tweets.jsonl

If you are interested in learning more it's probably best to read the Twitter documentation about it:

https://developer.twitter.com/en/docs/rate-limits

**Comment by SamHames** [comment]
Also, for the Twitter V2 API, hydration of tweets does not count towards
the cap.

**Comment by edsu** [comment]
@SamHames really? is that documented somewhere?

**Comment by SamHames** [comment]
Only the endpoints in this section count toward the tweet cap:
https://developer.twitter.com/en/docs/projects/overview#tweet-cap

Twitter has rearranged the docs a bit so it took forever to find that :(.
My memory is that it was included on each API endpoint page if it counted
toward the quota, but apparently not.

**Comment by debrajde1** [comment]
Thank you all for clarifying and resolving this! Its such a blessings to have such helpful and open community.

**Comment by debrajde1** [comment]
I am coming back again for another question. Sorry if there is any redundancy in my question. 

Say using "twarc hydrate tweet_ids.txt > tweet_ids__hydrated.jsonl" seems to have no cap limit as well as rate limit (at least way way faster than 900 queries per 15 minutes). It's downloading probably 500K tweets in 1-1.5 hours.   

Will same apply to "twarc**_2_** hydrate tweet_ids.txt > tweet_ids__hydrated.jsonl", i.e., no cap limit and apparently not much rate limit?

**Comment by igorbrigadir** [comment]
`twarc hydrate` uses https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-statuses-lookup so the max it can go to is 900 requests every 15 minutes, each request of 100 tweet ids. There is no monthly cap for v1.1 at all.

The rate you're getting is a bit high. Not sure why though.

`twarc2 hydrate` uses https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets which has the same rate limits, so i would expect it to go at the same 900 requests every 15 minutes speed. The monthly cap does not apply to this endpoint

Hope that helps!

**Comment by debrajde1** [comment]
This is extremely helpful. Thanks! 

With "twarc hydrate" I am getting little less than 500K tweets hydrated in 1.5 hours, which closely matches with what you said: "900 requests every 15 minutes, each request of 100 tweet ids". 

I will then try "twarc hydrate" for larger number of tweet ids. I was hesitant to use that, fearing I'll go beyond 500k monthly cap limit.
