### ISSUE TITLE
Enable --limit keyword argument for followers endpoint in Python client

### ISSUE THREAD

**Issue by JanaLasser** [DocNow/twarc#530]
I am very happy with the `--limit` option for the command line utility to cap the number of followers downloaded for a given user. As far as I can see, this option does not exist for the Python client. At least for my use cases, it would be nice to have.

**Comment by SamHames** [comment]
If you're using the following/follower method on the client, it might make more sense to do your own limiting based on the number of pages retrieved - if you post an example of what you're trying to do in code I might be able to update the docs to suggest a way to help.

**Comment by JanaLasser** [comment]
I wanted to limit the number of users retrieved in the first place. My main aim is to speed up querying the followers of a large number of users. I just need the latest 1000 followers of every user. First getting all of them and truncating later will slow things down significantly since the followers API has a rather strict limit of 15 requests per 15 minutes.

I ended up dowloading the followers in the terminal with the following command 
`twarc2 followers --limit 1000 <ID> <ID>.jsonl`

I wanted to do something like below in the client, but the `limit` kwarg is not supported.
`client.followers(<ID>, limit=1000)`

**Comment by SamHames** [comment]
If you're using the API directly, I'd recommend you use the pagination exposed by the library, rather than limiting to an exact number of followers, especially if you're looking to control the amount of API calls to get through a large number of users. The limit feature in the command line is a convenient approximation to this only. 

All of the library calls exposed on the client iterate through one page of results at a time, corresponding to one API call at a time. You're not required to run through every client call to completion if you don't want to. For example, for your purposes you could use the following to retrieve two pages of followers for a list of user_ids:

```python
user_ids = [1, 2, 3]

for user_id in user_ids:
    for i, follower_page in enumerate(client.followers(user_id)):
         <Do something with the follower_page here>
         if i == 2: # Only retrieve the first two pages
               break
```
I'm going to open a separate documentation ticket for this, because it's definitely a commonly used thing that we should provide some examples for.

**Comment by JanaLasser** [comment]
OK, that makes a lot of sense. Thank you for the hint!
