### ISSUE TITLE
Link search help to Twitter operator docs

### ISSUE THREAD

**Issue by NoeCampos22** [DocNow/twarc#571]
Hello! I would like to know if there are plans to add options like `--lang` to the commands `twarc2 search` or `twarc2 searches` or if this is too specific for the scope of twarc2 core?

I understand that with the Twitter APIv2 those "filters" are named operators and they are part of the query itself, instead of parameters on the url like on the APIv1. But I think It could be useful/practical to add these options to the search(es) commands, and make some string manipulation to complete the query that is feed into the request.

Let me know If you want me to elaborate something or to put some examples. In case it is on the scope, I would be happy to help implement them.

**Comment by SamHames** [comment]
Since they are search operators, I'd prefer not to have specific flags for
them at the command line - between field customisation, and existing API
options the command line already does a lot.

I think a great place to add this would be the documentation, as a
supplement to the Twitter search docs. I'm thinking a section about useful
search operators, with example queries?

**Comment by igorbrigadir** [comment]
Yeah, this is the page to look up for building queries: https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query so maybe we should link that in the doc string for `--help` too?

**Comment by NoeCampos22** [comment]
Okay, yeah, having examples using the different operators and/or the documentation link would be useful for new twarc users or just as a reference. 
Thanks!

**Comment by edsu** [comment]
I like the idea of linking `twarc2 search --help` to Twitter's search operator docs. I'm always having to search them up!
