### ISSUE TITLE
Count the number of tweets matching a language

### ISSUE THREAD

**Issue by Michael-Gauthier** [DocNow/twarc#625]
Hi everyone,

I know how to use `twarc2 counts` to count the number of tweets matching a query over a certain period of time, but is there a way to count the number of tweets emitted that match a certain language? I would like:

- Ideally, to have the number of tweets that have been emitted globally each month, in English
- If focusing on a specific language isn't possible, just the number of tweets emitted would be acceptable

I have been unable to find such stats online (I expected to find at least the number of tweets emitted monthly), and I am wondering if `twarc2 counts` allows for counts based on parameters other than strings. Using `twarc2 counts` with empty strings is apparently not possible, hence my question here, but as usual, I may have missed basic elements, so I apologize in advance if that is the case. 

Thanks in advance for any hint!

**Comment by igorbrigadir** [comment]
This is somewhat difficult, because the API will not let you make a general enough query to enumerate all English tweets, a few tricks that did work in the past: specifying `lang:en (I OR is OR the ...)` with a bunch of stopwords (lists here if you need: https://github.com/igorbrigadir/stopwords ) but these would miss a bunch of tweets, but would definitely get you within an order of magnitude of the real count I think

**Comment by SamHames** [comment]
I don't think there is any good way to do this. Igor's note about stopwords might approximate it, but Twitter V2 search requires you have at least one non-stopword term. 

Couple of options:
- Maybe you could build a long list of common words that aren't stopwords according to Twitter, but you wouldn't have any way to validate the counts resulting from that.
- You could measure proportions in the 1% sample stream rather than attempting to measure all of Twitter. This won't help if you want to do historical work though.

**Comment by Michael-Gauthier** [comment]
Thanks a lot for your help, the both of you! : )

Wow, I didn't realize this would be this difficult... Since there are online counts of the number of tweets sent each second, or how many have been sent today, I really expected to find historical records of those numbers.

I did realize that stopwords wouldn't work, because I tried doing some searches with empty words (i.e. ""), but I got the error message saying that it had to be a non-stopword, non-empty element...

Well, since what I want to do is a historical count, I guess this complicates things... Knowing these counts isn't crucial, it's just that it would help me highlight whether the topic I study has been more or less discussed over time, hence the need to know the overall number of tweets sent to know whether any increase in the number of tweets containing this topic is due to a greater interest in it, or just to a greater flow of tweets...

I'll still try to find ways, and if I find anything, I'll come back here to suggest it. Thanks a lot again for your help! : )
