### ISSUE TITLE
unauthorised response

### ISSUE THREAD

**Issue by msgyi** [DocNow/twarc#672]
Please i have academic access but i get unauthorised response after queries

**Comment by igorbrigadir** [comment]
I think this is the same thing, so following up there instead: https://twittercommunity.com/t/unauthorised-response-from-twarc/181258

**Comment by msgyi** [comment]
Hi  thanks a lot for the response.I have tried tweepy and   i have been
able to generate the data but the issue for me is how  to convert it to a
json file and then csv.

Thank you

**Comment by msgyi** [comment]
aLso  if  i want to retrieve tweets in a local language called twi  from
ghana, i
am currntly working on this code  to generate  twwets in this  language..
Any help, should add start time and end time. and then  some stop words as
well.Am new here.




query = '#joynews -is:retweet lang:"tw" "country":"gh"country_code": "gh"
U+1F600  "coordinates": "7.9465° N, 1.0232° W"
"country": "ghana",'
tweets = client.search_recent_tweets(query=query,
tweet_fields=['context_annotations', 'created_at'], max_results=100)

"""
What context_annotations are:
https://developer.twitter.com/en/docs/twitter-api/annotations/overview
"""
for tweet in tweets.data:
    print(tweet.text)
    if len(tweet.context_annotations) > 0:
        print(tweet.context_annotations)

**Comment by igorbrigadir** [comment]
There are several separate things here: 

If the same credentials and same queries etc work for tweepy then they should also work for twarc, if not, there is some more debugging to do to find out the root cause - this should not be happening.

For CSV conversion, twarc-csv should work. Otherwise you will need to do it manually with pandas or another library yourself. twarc-csv will work on json, but not tweepy data directly, so you would need to save the tweepy results as json: for any tweepy result, you should be able to access `._json` property of the object and save that in a file, and then use `twarc2 csv` on that. Unfortunately this requires a good bit more work than twarc directly, where any output file from `twarc2 search` commands can be the input to `twarc2 csv` commands.

The query you have is very ambiguous - there are several things here that should not be there, or should be specified in a different way. Maybe it's a copy paste error. What results are you looking for in general? It looks like you want to restrict results to everything from Ghana, so this is `place_country:gh` the other `country:` and `country_code` operators in the query are not valid. Specifying `coordinates` is also not a valid operator, it should be `point_radius:`, but coordinates are no longer used in twitter so there are likely no tweets that match those, so i wouldn't use that operator. The full list of valid query operators is here: https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#list the quotes in the query are not necessary unless you are enclosing multi word phrases. `lang:tw` is also ambiguous - `tw` is not a valid language code that can be searched on the API

> i want to retrieve tweets in a local language called twi 

The only valid languages to search for using `lang:` operator in the API are listed here beside `lang`: https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#list no other ones are possible, but to find some other language, you many need to search for some common words in that language instead.

The simplest way to do this with twarc, would be like this:

Install and configure everything (necessary to run even if you already done this part previously just to make sure):

```
pip install --upgrade twarc twarc-csv
twarc2 configure
```

Search and save some results from the last 7 days (should work even without academic access, the dates should be within the last week):

```
twarc2 search --start-time "2022-12-07" --end-time "2022-12-13" "#joynews -is:retweet place_country:gh" results.jsonl
```

Convert the tweets to CSV (at the time, there were just 24 results - place_country significantly reduces the result set because not all tweets have a location attached - very few do)

```
twarc2 csv results.jsonl results.csv
```

Hope that helps!

**Comment by msgyi** [comment]
Thanks a lot for taking the time to go through my codes, very generous .
 I  have installed twarc  again and was successful  on windows command
prompt  however the next  command   twarc2 configure is not working. snd
below are the results from the query. Thanks a lo.t


C:\Users\akosua> twarc2 configure
'twarc2' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\akosua>twarc2 configure
'twarc2' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\akosua>twarc configure
'twarc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\akosua>twarc
'twarc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by igorbrigadir** [comment]
> 'twarc2' is not recognized as an internal or external command, operable program or batch file. 

This error usually means that the executable was not correctly installed in the environment. 

Best thing to follow to trouble shoot is probably https://twarc-project.readthedocs.io/en/latest/windows10/

Or alternatively, what tends to work is installing Anaconda: https://docs.anaconda.com/anaconda/install/windows/ and then installing twarc with the pip commands inside Anaconda Prompt, that way worked before too.

**Comment by msgyi** [comment]
After downloading  python from the official page with the option  "add to
path" ticked,  the python --version  works on command line.

twarc was installed  but  after entering "twarc2 search blacklivesmatter" i
got "unauthorised " response. Ihave attached  a copy of the results

**Comment by msgyi** [comment]
[image: image.png]

**Comment by igorbrigadir** [comment]
Unfortunately there is no attachments here, because github does not read these from email replies, you will either have to attach this on https://github.com/DocNow/twarc/issues/672 directly, or better, visit https://docs.google.com/forms/d/e/1FAIpQLSf3E7PAXPoT-XoedpEy9UCTpDPS8kPj5JkMwpaWbuqVP0bTrQ/viewform to join the Slack, where it might be faster to go back and forth to debug this. I'm still sure it's not a bug in twarc because it works otherwise, and it's a matter of environments and setup.

**Comment by msgyi** [comment]
because i was giving my access codes in quotation marks that was a problem
for the authorization.I also installed python again and now my first trial
tweet has gone through. Thanks a lot , My main issue is the query that can
help me attain a large collection of tweets in a ghanaian language twi. Any
suggestions? Thanks.

**Comment by igorbrigadir** [comment]
Great! The best advice i can come up with for finding languages that twitter does not support, is trying to search for the most common words in the language, so for example, in English `(the OR of OR it OR and)` a query like that. In twi, this depends on the language - i think i was able to find a few tweets potentially in twi using this:

```
twarc2 search --archive "(Akwaaba OR Daabi OR nnwom OR \"Mepa wo kyɛw\" OR Asɔre)" akan_twi_test.jsonl
```

(But ideally using your own list of words and phrases, i just picked some randomly to illustrate from https://en.wikipedia.org/wiki/Akan_language - for phrases, like "Mepa wo kyɛw", note the need to use `\"` instead of `"` when using OR queries in twarc2 commands like that)

And once gathered, you'll then need to use your own ways of figuring out what results are useful and what results are not.

**Comment by msgyi** [comment]
Wow! thanks a lot, this is a good starter, Very insightful. Thanks will
continue on this path, guess will have to look at different hashtags and
@names and probably geolocation as well  to be able to  build  a large set
of tweets.

**Comment by msgyi** [comment]
HI
Please am having issues with this so help me

twarc2 search  --archive --start-time 2023-01-01 --end-time 2023-03-20
"(Akwaaba
OR Daabi OR nnwom OR \"Mepa wo kyɛw\" OR Asɔre OR wo OR wⴢ OR  nni OR me OR
di OR bⴢ OR  hⴢ OR  ho OR dabi OR kⴢ OR ni OR yɛ OR saa OR no OR te OR he OR
na OR de OR din OR hyɛ OR mu OR nso OR ɛyɛ OR bra OR wode OR sɛn OR akwaaba
OR aane OR kyɛw OR mepa OR bɛn OR ⴢdⴢ OR  frɛ OR  mewⴢ OR nante OR yie)"
owner.txt owner.json owner.csv
ERROR command prompt:
Error: Got unexpected extra arguments (owner.json owner.csv)
thanks

**Comment by igorbrigadir** [comment]
I think this should be 2 separate commands:

```
twarc2 search  --archive --start-time "2023-01-01" --end-time "2023-03-20" "(Akwaaba OR Daabi OR nnwom OR \"Mepa wo kyɛw\" OR Asɔre OR wo OR wⴢ OR  nni OR di OR bⴢ OR  hⴢ OR ho OR dabi OR kⴢ OR ni OR yɛ OR saa OR te OR na OR de OR din OR hyɛ OR mu OR nso OR ɛyɛ OR bra OR wode OR sɛn OR akwaaba OR aane OR kyɛw OR mepa OR bɛn OR ⴢdⴢ OR  frɛ OR  mewⴢ OR nante OR yie)" owner.jsonl
```

This will create `owner.jsonl` with tweet results.

I removed `OR me` because i think that would ruin the results because that would get too many false English tweets. The same thing may be for `de` or `no`, or `he`, and maybe a few others - i think these need a second look to make sure you're not going to get too many false positives.

To convert to csv,

```
twarc2 csv owner.jsonl owner.csv
```

Hope that helps!

**Comment by msgyi** [comment]
Thank you  for your  insight
